[build]
# Use -static if it becomes a thing. https://github.com/golang/go/issues/26492
command = "go build -tags netlify,osusergo,netgo -o netlify/functions/all ."

[build.environment]
GO_VERSION = "1.24.1"
GO_IMPORT_PATH = "github.com/jcbhmr/goghr.jcbhmr.com"

[[redirects]]
from = "/*"
to = "/.netlify/functions/all/:splat"
status = 200
