[build]
command = "go build -tags netlify,osusergo,netgo -ldflags=-extldflags=-static -o netlify/functions/all ."

[build.environment]
GO_VERSION = "1.24.1"
GO_IMPORT_PATH = "github.com/jcbhmr/goghr.jcbhmr.com"

[[redirects]]
from = "/*"
to = "/.netlify/functions/all/:splat"
status = 200
