[build]
# TODO: Build on amazonlinux to match glibc etc.
# https://github.com/golang/go/issues/26492
command = "go build -tags lambda,netgo -o netlify/functions/all ./cmd/ghreleasemodproxy"

[build.environment]
GO_VERSION = "1.24.1"

[[redirects]]
from = "/*"
to = "/.netlify/functions/all/:splat"
status = 200
